# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hrbcpp <- function(y, x, K, L, res, c, p, q, h, b) {
    .Call('nprobust_hrbcpp', PACKAGE = 'nprobust', y, x, K, L, res, c, p, q, h, b)
}

